# Generated by Django 5.1.5 on 2025-02-16 22:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('organizations', '0003_delete_organizationmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationApplication',
            new_name='Application',
        ),
    ]
