# Generated by Django 5.1.5 on 2025-02-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmembership_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationMembership',
        ),
    ]
